### ISSUE TITLE
It should be clear when a Patreon feature isn't available to your level

### ISSUE THREAD

**Issue by globau** [JustPugDev/AUSMPBugs#3]
It should be clear when a Patreon feature isn't available to your level.

Currently it just plays the _Item Breaking_ sound; it would be nice if a message was displayed at the same time.

Alternatives:
- group patreon features by level (eg. a "Stone and Higher" menu, etc)
- hide, dim, or desaturate unavailable features

**Comment by JustPugDev** [comment]
Will make a Red Icon if the cosmetic isn't available for Patreon
